import { useState, useMemo } from 'react'
import { useTranslation } from 'react-i18next'
import SearchOutlinedIcon from '@mui/icons-material/SearchOutlined'
import AgentCard, { AgentDef } from '../components/AgentCard'

interface AgentEntry extends AgentDef {
  category: string
}

const agents: AgentEntry[] = [
  {
    name: 'Self-Healing Locator',
    category: 'locator',
    description:
      'When a Playwright test fails because the UI changed, this agent suggests a new getByRole / getByTestId locator from stripped DOM context using Claude.',
    status: 'active',
    runId: 'healing',
    runCommand: 'npx tsx src/agents/self-healing.ts',
    systemPrompt:
      'You are a senior Playwright automation engineer. Given a failed locator and a DOM snapshot, suggest the single best alternative locator using getByRole, getByLabel, or getByTestId. Return only the locator string, no explanation.',
    toolSchema: {
      name: 'self_healing_locator',
      description: 'Suggests a new Playwright locator when the current one fails due to UI changes.',
      input_schema: {
        type: 'object',
        properties: {
          failed_locator: { type: 'string', description: 'The locator that failed' },
          dom_snapshot: { type: 'string', description: 'Stripped DOM context around the target element' },
        },
        required: ['failed_locator', 'dom_snapshot'],
      },
    },
  },
  {
    name: 'Automated Bug Triage',
    category: 'triage',
    description:
      'Reads an error log file and writes a Jira-ready Markdown report with root-cause analysis, severity classification, and reproduction steps.',
    status: 'active',
    runId: 'triage',
    runCommand: 'npx tsx src/skills/log-analyzer.ts',
    systemPrompt:
      'You are an elite QA engineer. Read the error log and produce a structured bug report: Title, Severity (P0–P3), Summary, Root Cause, Steps to Reproduce, Expected vs Actual, Environment. Output clean Markdown.',
    toolSchema: {
      name: 'automated_bug_triage',
      description: 'Analyzes error logs and generates Jira-ready bug reports.',
      input_schema: {
        type: 'object',
        properties: {
          log_content: { type: 'string', description: 'Raw error log content' },
        },
        required: ['log_content'],
      },
    },
  },
  {
    name: 'Auto-POM Builder',
    category: 'architecture',
    description:
      'Paste DOM HTML and get a complete TypeScript Playwright Page Object Model class with getByRole locators and async action methods — generated by Claude.',
    status: 'active',
    runId: 'auto-pom',
    runCommand: 'npx tsx src/agents/auto-pom/index.ts',
    systemPrompt:
      'You are a Playwright architect. Given a DOM snapshot, generate a complete TypeScript Page Object Model class with getByRole locators and async action methods. Follow POM best practices.',
    toolSchema: {
      name: 'auto_pom_builder',
      description: 'Generates a TypeScript Playwright POM class from a DOM snapshot.',
      input_schema: {
        type: 'object',
        properties: {
          dom_html: { type: 'string', description: 'HTML snapshot of the page' },
          page_name: { type: 'string', description: 'Class name for the POM (e.g. LoginPage)' },
        },
        required: ['dom_html', 'page_name'],
      },
    },
  },
  {
    name: 'Visual Regression Agent',
    category: 'visual',
    description:
      'Compares baseline screenshots against current versions, quantifies pixel differences, assigns severity, and produces a Markdown regression report.',
    status: 'active',
    runId: 'visual-regression',
    runCommand: 'npx tsx src/agents/visual-regression/index.ts',
    systemPrompt:
      'You are a visual QA engineer. Analyze screenshot differences, categorize severity, and recommend whether to approve or reject each visual change.',
    toolSchema: {
      name: 'visual_regression_agent',
      description: 'Compares screenshots and generates a visual regression report.',
      input_schema: {
        type: 'object',
        properties: {
          baseline_path: { type: 'string', description: 'Path to baseline screenshot' },
          current_path: { type: 'string', description: 'Path to current screenshot' },
        },
        required: ['baseline_path', 'current_path'],
      },
    },
  },
  {
    name: 'Visual A11y Scanner',
    category: 'visual',
    description:
      'Analyzes a page DOM for WCAG 2.1 AA violations and produces a prioritized accessibility report with element-level fix recommendations.',
    status: 'active',
    runId: 'a11y',
    runCommand: 'npx tsx src/agents/visual-a11y/index.ts',
    systemPrompt:
      'You are an accessibility expert. Analyze the screenshot and DOM and produce a WCAG 2.1 AA compliance report with specific violation descriptions and code-level fix recommendations.',
    toolSchema: {
      name: 'visual_a11y_scanner',
      description: 'Scans a page for WCAG 2.1 AA accessibility violations.',
      input_schema: {
        type: 'object',
        properties: {
          url: { type: 'string', description: 'URL to scan' },
          standard: { type: 'string', enum: ['WCAG21AA', 'WCAG21A'], description: 'WCAG standard level' },
        },
        required: ['url'],
      },
    },
  },
  {
    name: 'Network Interceptor & Mock Gen',
    category: 'network',
    description:
      'Analyzes a Playwright network trace and generates MSW/Playwright mock handlers for all captured API endpoints.',
    status: 'planned',
    runCommand: 'npx tsx scripts/network-mock-gen.ts --trace <trace.zip>',
    systemPrompt:
      'You are an API mocking specialist. Given a HAR or Playwright trace, generate Playwright route intercept handlers in TypeScript for every unique API endpoint found.',
  },
  {
    name: 'Chaos Monkey UI',
    category: 'chaos',
    description:
      'Randomly interacts with UI elements, captures unexpected errors and console exceptions, and reports all anomalies found during the chaos session.',
    status: 'planned',
    runCommand: 'npx tsx scripts/chaos-monkey-ui.ts --duration 120',
    systemPrompt:
      'You are a chaos engineering agent. After each random UI interaction, evaluate whether any console errors, network failures, or visible anomalies occurred. Document each finding with a screenshot and reproduction path.',
  },
]

const ALL_CATEGORIES = ['all', ...Array.from(new Set(agents.map((a) => a.category)))]

export default function AgentsPage() {
  const { t } = useTranslation()
  const [search, setSearch] = useState('')
  const [activeCategory, setActiveCategory] = useState('all')

  const filtered = useMemo(() => {
    const q = search.toLowerCase()
    return agents.filter((a) => {
      const matchesSearch = !q || a.name.toLowerCase().includes(q) || a.description.toLowerCase().includes(q)
      const matchesCategory = activeCategory === 'all' || a.category === activeCategory
      return matchesSearch && matchesCategory
    })
  }, [search, activeCategory])

  const active = agents.filter((a) => a.status === 'active')
  const planned = agents.filter((a) => a.status === 'planned')

  return (
    <div className="max-w-5xl mx-auto px-4 py-12 animate-fade-up">
      <div className="mb-8">
        <h1 className="text-2xl font-bold mb-2" style={{ color: 'var(--text-main)' }}>
          {t('agents.title')}
        </h1>
        <p className="text-sm" style={{ color: 'var(--text-muted)' }}>
          {t('agents.subtitle', { active: active.length, planned: planned.length })}
        </p>
      </div>

      {/* Search + filters */}
      <div className="mb-6 flex flex-col sm:flex-row gap-3">
        <div
          className="relative flex-1"
        >
          <SearchOutlinedIcon
            sx={{ fontSize: 16 }}
            className="absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none"
            style={{ color: 'var(--text-muted)' }}
          />
          <input
            type="text"
            placeholder={t('agents.search_placeholder')}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-8 pr-3 py-2 text-sm rounded-xl border outline-none focus:ring-2 focus:ring-primary-300"
            style={{
              borderColor: 'var(--border)',
              backgroundColor: 'var(--bg-card)',
              color: 'var(--text-main)',
            }}
          />
        </div>
        <div className="flex flex-wrap gap-1.5">
          {ALL_CATEGORIES.map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium capitalize transition-all duration-150 ${
                activeCategory === cat
                  ? 'bg-primary-600 text-white shadow-soft'
                  : 'hover:bg-sand-400'
              }`}
              style={activeCategory === cat ? {} : { color: 'var(--text-muted)', borderColor: 'var(--border)' }}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {filtered.length === 0 ? (
        <p className="text-sm text-center py-16" style={{ color: 'var(--text-muted)' }}>
          {t('agents.no_match')}
        </p>
      ) : (
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {filtered.map((agent) => (
            <AgentCard key={agent.name} agent={agent} />
          ))}
        </div>
      )}
    </div>
  )
}
